services:
  postgres_raliz:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    command: postgres -c 'max_connections=100'

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge